# This workflow is triggered whenever "Caller Arm Virtual Hardware blinky example" workflow is completed (which is called by PR).
# This workflow ideally should be triggered also by PR, but forked PR has limited permissions which does not
# allow to use `configure-aws-credentials` actions and using secrets.
# It will update its status back to the caller PR as "Arm Virtual Hardware blinky example" check name

# This is a basic workflow to help you get started with Actions on CMSIS projects
# See also https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/infrastructure-for-continuous-integration-tests
#
# The repository needs to provide the following secrets
# - AWS_ACCESS_KEY_ID           The id of the access key.
# - AWS_SECRET_ACCESS_KEY       The access key secret.
# - AWS_DEFAULT_REGION          The data center region to be used.
# - AWS_S3_BUCKET_NAME          The name of the S3 storage bucket to be used for data exchange.
# - AWS_IAM_PROFILE             The IAM profile to be used.
# - AWS_SECURITY_GROUP_ID       The id of the security group to add the EC2 instance to.
# - AWS_SUBNET_ID               The id of the network subnet to connect the EC2 instance to.
# - ARM_UBL                     A bzip2 compressed and base64-encoded user based license file:
#                               armlm activate --server <URL> --product <PRODUCT> --as-user ubuntu --to-file ubuntu-ubl.binlic
#                               bzip2 -c ubuntu-ubl.binlic | base64 > ubuntu-ubl.binlic.bz2.b64

name: Arm Virtual Hardware Blinky example
on:
  workflow_run:
    workflows:
      - Caller Arm Virtual Hardware blinky example
    types:
      - completed
  workflow_dispatch:

env:
  # Enable the next three lines if you are using IAM User and you added them in the repo's secret.
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_IAM_PROFILE: ${{ secrets.AWS_IAM_PROFILE }}
  AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
  AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
  ARM_UBL: ${{ secrets.ARM_UBL }}

jobs:
  set_pending_status_to_pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: Set a pending status to the PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header 'content-type: application/json' \
            --data '{
              "state": "pending",
              "context": "Arm Virtual Hardware blinky example",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id	}}"
              }' \
            --fail

  ci_test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Read github.event
      run: echo "${{ github.event.workflow_run.event }}"
    - name: Check out repository code
      if: ${{ github.event.workflow_run.event != 'pull_request' }}
      uses: actions/checkout@v3

    - name: Download workflow artifact
      if: ${{ github.event.workflow_run.event == 'pull_request' }}
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: caller_virtual_hardware.yml
        run_id: ${{ github.event.workflow_run.id }}

    - name: Read the pr_num file
      if: ${{ github.event.workflow_run.event == 'pull_request' }}
      id: pr_num_reader
      uses: juliangruber/read-file-action@v1.1.6
      with:
        path: ./pr_number/pr_number
        trim: true

    - name: Clone this repo
      if: ${{ github.event.workflow_run.event == 'pull_request' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout PR
      if: ${{ github.event.workflow_run.event == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        gh pr checkout ${{ steps.pr_num_reader.outputs.content }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::720528183931:role/Proj-vht-assume-role
        aws-region: eu-west-1

    - name: Install AVH Client for Python
      run: |
        pip install git+https://github.com/ARM-software/avhclient.git@v0.1

    - uses: ammaraskar/gcc-problem-matcher@master

    - name: Run tests
      id: avh
      run: |
        printenv ARM_UBL | base64 -d | bunzip2 > Blinky_Cortex-M85/ubuntu-ubl.binlic
        avhclient -b aws execute --specfile Blinky_Cortex-M85/avh.yml
        count=$(grep -c "LED" Blinky_Cortex-M85/vht.log)
        echo "Found 'LED' ${count} times in vht.log ..."
        if [[ $count < 19 ]]; then
          echo "... this is less than the expected 19 times!"
          exit 1
        fi

    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: |
          Blinky_Cortex-M85/Objects/Blinky.axf
          Blinky_Cortex-M85/Objects/Blinky.axf.map
          Blinky_Cortex-M85/EventRecorder.log
          Blinky_Cortex-M85/vht.log
        retention-days: 1
        if-no-files-found: error
      if: always()
